### ISSUE TITLE
Switch to new resource monitor snapshots

### ISSUE THREAD

**Issue by matz-e** [matz-e/lobster#605]
As per meeting of Oct 05, 2017, we should replace our own accounting with the new snapshots feature of WQ.

## TODO for documentation/draft:

- [ ] Find WQ documentation about this
- [ ] Add more to the TODO list below

## Things to be implemented

- [ ] Setup on the master
  - [ ] Add `get_resource_monitor_setup` method to the [workflow](https://github.com/matz-e/lobster/blob/master/lobster/core/workflow.py)
  - [ ] Pass setup [here](https://github.com/matz-e/lobster/blob/master/lobster/core/workflow.py) back to the "main loop"
  - [ ] Take setup and mangle it, add to the actual task object
- [ ] Adapt worker `wrapper.sh`
  - [ ] [Replace wrapper start with WQ trigger](https://github.com/matz-e/lobster/blob/master/lobster/core/data/wrapper.sh#L28)
  - [ ] [Replace wrapper end with WQ trigger](https://github.com/matz-e/lobster/blob/master/lobster/core/data/wrapper.sh#L162)
- [ ] Adapt worker `task.py`
  - [ ] [Remove wrapper time extraction](https://github.com/matz-e/lobster/blob/master/lobster/core/data/task.py#L796)
  - [ ] [Remove CMSSW log time extraction](https://github.com/matz-e/lobster/blob/master/lobster/core/data/task.py#L806)
  - [ ] [Remove time data stubs](https://github.com/matz-e/lobster/blob/master/lobster/core/data/task.py#L1050)
  - [ ] Replace all mentions of `task_timing` with WQ triggers
- [ ] Collection on the master
- [ ] Plotting

**Comment by matz-e** [comment]
Not sure if updates trigger notifications… I filled out more of the list of stuff needing to be done.
